### PR TITLE
Add color to Exception message

### PR DESCRIPTION
**Pull request by zhaihj**
2015-01-30-095632_930x361_scrot

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Any progress on this? It's something I'd really like to see

**Comment by zhaihj** [comment]
It's here just because no one merge or reject it....

**Comment by kirbyfan64** [comment]
Who's the one who merges these things?

Last time for me a PR didn't get merged, it was that it got lost in the maintainer's email. I used the at-sign to reference him, and he merged it.

**Comment by davidhesselbom** [comment]
Same guy who owns the repo, in this case.

**Comment by fasterthanlime** [comment]
Hi! that guy here. I'll try and take some time to merge it this week. No promises, work's busy & am sick atm. Sorry for the delay(s).

**Pull request closed without merging**
