### PR TITLE
Added support for the null coalescing operator ??

### PR DESCRIPTION
**Pull request by alexnask**

### CODE REVIEW

**Comment by davidhesselbom** [comment]
No one updated https://github.com/fasterthanlime/nagaqueen, did they?

**Comment by shamanas** [comment]
@davidhesselbom  https://github.com/fasterthanlime/nagaqueen/blob/master/grammar/nagaqueen.leg#L1366  

It's there!

**Comment by davidhesselbom** [comment]
Wait, it was added in... um. I don't know what I was thinking, this is over a year old and so is the commit in NagaQueen. Forget I said anything :P

**Comment by shamanas** [comment]
Haha no worries, I missed the Nagaqueen.c diff too for a bit and was wondering if it was pushed before it got implemented in rock ^^

**Comment by shamanas** [comment]
@davidhesselbom I think there is a double evaluation bug with it still, I'll take a look at it right now  

(I think I naively translated `a ?? b` to `a != null ? a : b` without taking the side effects of a into account)

**Comment by davidhesselbom** [comment]
You did...

```ooc
honk: func -> Bool { println("honk"); true }
toot := honk() ?? false
```
prints
```
honk
honk
```
but it should only do it once.

**Comment by davidhesselbom** [comment]
Also, your test includes this line:
```ooc
if ((1 ?? 2 ?? 3) != 3)
```
which gives me the following warnings:
```
test.ooc: In function ‘test_rtest_load’:
test.ooc:7:19: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 if ((1 ?? 2 ?? 3) != 3)
                   ^
test.ooc:7:55: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 if ((1 ?? 2 ?? 3) != 3)
                                                       ^

```

**Comment by shamanas** [comment]
Huh, interesting how the operator works with bool too, probably because I actually translate to `a ? a : b`, I'm not sure if even that is intended.  

Translating to

```ooc
a_temp : typeof(a)

... (a_temp = a, a_temp ? a_temp : b) ...
```  

Should do the trick, grabbing a coffee and going to town :)

**Comment by shamanas** [comment]
I don't get warnings on my test but I could see how you would if you ignore the overload  

```ooc
operator ?? (l, r: Int) -> Int { r }
```

In which case you are comparing integers to null, thus "cast from pointer to integer of different size"

**Comment by davidhesselbom** [comment]
Ah, yes, I did, I just took that one line from the test file. That explains it.

**Comment by shamanas** [comment]
Should be somewhat better to use now!

**Pull request merged**
